version: '3'
services:
  proguard:
    build: .
    container_name: proguard
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./workdir:/app/workdir
      - ./start.sh:/app/start.sh
